[tool.poetry]
name = "icog"
version = "0.1.0"
description = ""
authors = ["Martin Esparza <martinesparza22.me@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.25.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
